# Generated by Django 3.0.4 on 2020-03-24 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200322_1732'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagPetition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('petition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Petition')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Tag')),
            ],
        ),
        migrations.CreateModel(
            name='TagOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Offer')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Tag')),
            ],
        ),
    ]
