# Generated by Django 3.0.4 on 2020-03-28 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_tagoffer_tagpetition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='name',
        ),
        migrations.AddField(
            model_name='offer',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='title',
            field=models.CharField(default='test', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='provider',
            name='provider_main_img',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
