# Generated by Django 3.0.4 on 2020-03-28 20:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200328_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='start_date',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
    ]
