# Generated by Django 3.0.4 on 2020-03-29 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20200329_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='petition',
            name='added_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Petition'),
        ),
    ]
