# Generated by Django 3.0.4 on 2020-04-07 12:50

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20200406_2304'),
    ]

    operations = [
        migrations.AddField(
            model_name='productitem',
            name='affiliate_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('order_main_img', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('start_date', models.DateTimeField(default=datetime.datetime.now)),
                ('url', models.CharField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(default='new', max_length=25)),
                ('petition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Petition')),
                ('product_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OfferReaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='accepted', max_length=25)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('message', models.TextField(blank=True, null=True)),
                ('offer_petition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Petition')),
            ],
        ),
        migrations.CreateModel(
            name='Following',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='accepted', max_length=15)),
                ('petition_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('relation_date', models.DateTimeField(blank=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('following_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='following_to', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='me', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['petition_date'],
            },
        ),
    ]
