# Generated by Django 3.0.4 on 2020-04-07 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20200407_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='following',
            name='relation_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
