# Generated by Django 3.0.4 on 2020-04-09 12:23

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20200407_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='petition',
            name='privacy',
            field=models.CharField(default='public', max_length=15),
        ),
        migrations.AddField(
            model_name='place',
            name='visibility',
            field=models.CharField(default='public', max_length=25),
        ),
        migrations.CreateModel(
            name='FollowingProvider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='accepted', max_length=15)),
                ('petition_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('relation_date', models.DateTimeField(blank=True, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('provider', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Provider')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['petition_date'],
            },
        ),
        migrations.CreateModel(
            name='FollowingPlace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='accepted', max_length=15)),
                ('petition_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('relation_date', models.DateTimeField(blank=True, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('place', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Place')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['petition_date'],
            },
        ),
    ]
