# Generated by Django 3.0.4 on 2020-04-09 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_auto_20200409_1223'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='spouse_name',
            new_name='alias',
        ),
    ]
