# Generated by Django 3.0.4 on 2020-04-11 10:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_auto_20200411_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='creation_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
