# Generated by Django 3.0.4 on 2020-04-14 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_place_creation_date'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='following',
            constraint=models.UniqueConstraint(fields=('user', 'following_to'), name='unique following'),
        ),
        migrations.AlterModelTable(
            name='following',
            table='users_following',
        ),
    ]
