# Generated by Django 3.0.4 on 2020-05-08 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_auto_20200425_0901'),
    ]

    operations = [
        migrations.AddField(
            model_name='petition',
            name='tags',
            field=models.ManyToManyField(to='users.Tag'),
        ),
    ]
